#!/usr/bin/env python2
# written by Moses Arocha
# Written with the help of TJ O'Connor in his book "Violent Python"

from scapy.all import *

def testTTL(pkt):
	try:
		if pkt.haslayer(IP):
			ipsrc = pkt.getlayer(IP).src
			ttl = str(pkt.ttl)
			print '\t [Success] Packet Received From: '+ipsrc+' with TTL of : '+ttl
	except:
		pass

def main():
	sniff(prn=testTTL, store=0)

if __name__ == '__main__':
	main()
